name: ChronoLab
description: "A timers for laboratories"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  wakelock_plus: ^1.2.0
  flutter_local_notifications: ^18.0.1
  vibration: ^2.0.0
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  path_provider: ^2.1.3
  share_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/sounds/
